### ISSUE TITLE
No Export Content on Windows 10

### ISSUE THREAD

**Issue by TrevorCash** [StefanTraistaru/batch-export#12] opened 2021-07-08 15:38 UTC
I get a crash when I export my drawing on windows 10.   I'm exporting layers as SVG's.  The files appear to get written but with no contents, here is one of the output files:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   width="79.110741mm"
   height="280.30972mm"
   viewBox="0 0 79.110741 280.30971"
   version="1.1"
   id="svg8">
  <defs
     id="defs2" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title />
      </cc:Work>
    </rdf:RDF>
  </metadata>
</svg>
```

Here is the attached drawing I am using.
[EuroPlate_Art_and_Cuts.zip](https://github.com/StefanTraistaru/batch-export/files/6785722/EuroPlate_Art_and_Cuts.zip)

Settings:
![image](https://user-images.githubusercontent.com/2559371/124950529-ba321200-dfcf-11eb-9c46-0dd79c1fce69.png)

Inscape Version:
![image](https://user-images.githubusercontent.com/2559371/124950285-80610b80-dfcf-11eb-934b-04934b67635f.png)

Thanks for you help,
Trevor

**Comment by StefanTraistaru** [comment] 2021-07-15 11:14
Hi Trevor,

Thanks for the detailed issue. The fact that you included the source file definitely helped a lot.

I was able to reproduce the issue on Linux as well and I think it is a problem with the grouped layers. I will update this issue once I manage to solve it.

Workaround: Ungroup layers and have them all on the same hierarchical level. Make sure you have a backup of your original file before as this will mess with you layer structure. Just use the extension and it will work as intended.

**Comment by StefanTraistaru** [comment] 2021-07-19 13:34
I fixed the problem and added a new option that you can choose from in order to make exports based on the hierarchical structure of the layers. You can find the updated version on the Inkscape website as well.

I will close this issue now. Feel free to reopen it if you have any questions.

**Closed by StefanTraistaru** 2021-07-19 13:34 UTC
